// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "ada9aba5bd8465440f53160ad6b5c6c5"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"f8fd0b15d764fd84d0d8f23004b2ede5": "1f8b08000000000000ff010000ffff0000000000000000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("stuff to copy", "./assets")
		b.SetResolver("junk-from-packr2.txt", packr.Pointer{ForwardBox: gk, ForwardPath: "f8fd0b15d764fd84d0d8f23004b2ede5"})
		}()

	return nil
}()
